basePath: /api
definitions:
  model.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  model.UserLoginResponse:
    properties:
      token:
        type: string
    type: object
  rest_err.Causes:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  rest_err.RestErr:
    properties:
      causes:
        items:
          $ref: '#/definitions/rest_err.Causes'
        type: array
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API de exemplo com documentação Swagger em Go.
  title: API CRUD GO
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: Autentica um usuário e retorna o token
      parameters:
      - description: Informações de login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserLoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Login de usuário
      tags:
      - Autenticação
swagger: "2.0"
